---

- name: Install PostgreSQL
  tags:
    - system
    - pkgs
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - postgresql-server
    - postgresql-contrib
    - py-psycopg2
    - ruby24-pg

- name: Run initial config
  file: name={{ postgres_datadir | default('/var/postgresql/data') }} state=directory owner=_postgresql group=_postgresql
  register: made_pgdir

- name: Init database
  shell: "initdb -D {{ postgres_datadir | default('/var/postgresql/data') }} -E UTF8 -A md5  --auth-local=trust -U postgres"
  become: true
  become_user: _postgresql
  become_method: su
  args:
    creates: "{{ postgres_datadir | default('/var/postgresql/data') }}/pg_hba.conf"

- name: Install pg_hba.conf
  copy:
    src: pg_hba.conf
    dest: "{{ postgres_datadir | default('/var/postgresql/data') }}/pg_hba.conf"

- name: Enable postgresql
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create database user
  postgresql_user:
    name: mastodon
    role_attr_flags: CREATEDB
