---

- name: Install pre-reqs
  tags:
    - system
    - pkgs
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - ImageMagick
    - autoconf-2.69p2
    - automake-1.15.1
    - bwm-ng
    - ffmpeg
    - gcc
    - git
    - gnupg-2.2.4
    - icu4c
    - libidn
    - node
    - protobuf
    - ruby24-addressable
    - ruby24-bundler
    - ruby24-nokogiri
    - ruby24-puma
    - ruby24-sanitize

- name: Make symlinks
  file:
    state: link
    src: "/usr/local/bin/{{ item.src }}"
    dest: "/usr/local/bin/{{ item.dest }}"
  with_items:
    - { src: "python2.7", dest: "python" }
    - { src: "bundle24", dest: "bundle" }

- name: Configure login.conf
  tags:
    - system
    - login.conf
  copy:
    src: login.conf
    dest: /etc/login.conf
    owner: root
    group: wheel
    mode: 0644

- name: Add _mastodon group
  group:
    name: _mastodon
    state: present

- name: Add _mastodon user
  tags:
    - system
  user:
    name: _mastodon
    shell: /bin/ksh
    home: /var/www/_mastodon
    state: present
    group: _mastodon
    login_class: mastodon
