---

- name: Add profile for _mastodon
  tags:
    - profile
  copy:
    dest: /var/www/_mastodon/.profile
    owner: _mastodon
    group: daemon
    content: |
            PATH=$HOME/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin:/usr/games:.
            export PATH HOME TERM
            export CC=/usr/bin/clang
            export CXX=/usr/bin/clang++
            #export AUTOCONF_VERSION=2.69
            #export AUTOMAKE_VERSION=1.15
            export RAIL_ENV=production
            export NODE_ENV=production
            export DB_POOL=5

# https://github.com/ansible/ansible/issues/27520
- name: Reset ssh connection
  meta: reset_connection

- name: Create .gitconfig
  copy:
    dest: /var/www/_mastodon/.gitconfig
    owner: _mastodon
    group: daemon
    content: |
            [gpg]
                program = /usr/local/bin/gpg2
            [transfer]
                fsckobjects = true
            [fetch]
                fsckobjects = true

- name: Copy github's gpg pubkey
  tags:
    - code
  copy:
    src: pubkey.asc
    dest: /var/www/_mastodon/pubkey.asc
    owner: _mastodon

- name: Import github's gpg key
  tags:
    - code
  become: true
  become_method: su
  become_user: _mastodon
  command: 'gpg2 --import /var/www/_mastodon/pubkey.asc'
  register: gpg_output
  changed_when: "'imported: 1' in gpg_output.stderr"

- name: Install "yarn" node.js package globally.
  tags:
    - system
  npm:
    name: yarn
    global: yes

- name: Clone mastodon repo
  tags:
    - code
  become: true
  become_method: su
  become_user: _mastodon
  git:
    repo: https://github.com/tootsuite/mastodon.git
    dest: /var/www/_mastodon/live
    verify_commit: true
    version: "{{ mastodon_release | default('master') }}"

- name: Copy rake helper script
  copy:
    src: rake_runner.sh
    dest: /var/www/_mastodon/rake_runner.sh
    mode: 0755
    owner: "_mastodon"

- name: Run Bundle
  tags:
    - bundle
    - deps
  become: true
  become_method: su
  become_user: "_mastodon"
  command: "bundle24 install --deployment --without development test"
  args:
    chdir: /var/www/_mastodon/live
    creates: /var/www/_mastodon/live/vendor/bundle/

- name: Run Yarn
  tags:
    - bundle
    - deps
  become: true
  become_method: su
  become_user: "_mastodon"
  command: "yarn install --pure-lockfile"
  args:
    chdir: /var/www/_mastodon/live
    creates: /var/www/_mastodon/live/node_modules/

- name: Create mastodon env.production file
  tags:
    - secrets
    - env
    - rake
  template:
    src: env.production.j2
    dest: /var/www/_mastodon/live/.env.production
    owner: _mastodon
    group: www
    mode: 0640

- name: Copy rake helper script
  copy:
    src: rake_runner.sh
    dest: /var/www/_mastodon/rake_runner.sh
    mode: 0755
    owner: "_mastodon"

- name: Copy tmux start script
  copy:
    src: starter.sh
    dest: /var/www/_mastodon/starter.sh
    mode: 0755
    owner: "_mastodon"

- name: Setup DB
  tags:
    - db
  become: true
  become_method: su
  become_user: "_mastodon"
  shell: "/var/www/_mastodon/rake_runner.sh db"
  args:
    chdir: /var/www/_mastodon/live
    creates: /var/www/_mastodon/db

- name: Setup JS / CSS
  tags:
    - cssjs
  become: true
  become_method: su
  become_user: "_mastodon"
  shell: "/var/www/_mastodon/rake_runner.sh cssjs"
  ignore_errors: True
  args:
    chdir: /var/www/_mastodon/live
    creates: /var/www/_mastodon/cssjs

